version: 2.1
orbs:
  cypress: cypress-io/cypress@1.23.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      # https://github.com/facebook/create-react-app/issues/8688#issuecomment-620607944
      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
      - run: yarn lint
      - run: yarn ci
